export const arry = [
  "AC Repair",
  "Accessories",
  "Body Repair",
  "Car Detailing",
  "Car Wash",
  "Collision Repair",
  "Custom Modification",
  "Electrical",
  "Flooded Car Repair",
  "Glass Repair",
  "Heating/Cooling",
  "Mechanical",
  "MOT Test",
  "Oil Chnage",
  "Paint Shop",
  "Pre-purchase test",
  "Roadside Assistance",
  "RTA registration",
  "Spare Parts",
  "Tire Shop",
  "Vehicle Import",
  "Towing to shop",
  "Used cars trade",
  "Vehicle Interiors",
  "Window Tints",
];

 export const arry1 = [
  "Pick-Up & Drop-Off (free)",
  "Pick-Up & Drop-Off (Charged)",
  "Service Contract",
  "Express Servicing",
  "Mobile Mechanics (service at doorsteps)",
];
